# svamp
## SDP 
### Codellama
prefix='ppo_paper_final_new/_models_outputs_sft/svamp_python_sdp_codellama' \
ckpt_name='global_step_128_epoch_2' \
input_path='data/svamp_python_sdp.json' \
engine='python' \
batch_size='2' \
max_length='1024' \
num_return_sequences='100' \
do_sample='1' \
    bash exps/paper_exps/Sampling/_template.sh

### Galactica
prefix='ppo_paper_final_new/_models_outputs_sft/svamp_python_sdp_galactica' \
ckpt_name='global_step_128_epoch_2' \
input_path='data/svamp_python_sdp.json' \
engine='python' \
batch_size='2' \
max_length='1024' \
num_return_sequences='100' \
do_sample='1' \
    bash exps/paper_exps/Sampling/_template.sh

## NL 
### Codellama
prefix='ppo_paper_final_new/_models_outputs_sft/svamp_nl_codellama' \
ckpt_name='global_step_130_epoch_2' \
input_path='data/svamp_nl.json' \
engine='nl' \
batch_size='2' \
max_length='1024' \
num_return_sequences='100' \
do_sample='1' \
    bash exps/paper_exps/Sampling/_template.sh

### Galactica
prefix='ppo_paper_final_new/_models_outputs_sft/svamp_nl_galactica' \
ckpt_name='global_step_130_epoch_2' \
input_path='data/svamp_nl.json' \
engine='nl' \
batch_size='2' \
max_length='1024' \
num_return_sequences='100' \
do_sample='1' \
    bash exps/paper_exps/Sampling/_template.sh